lvim.builtin.indentlines.options = {
  char = "▎",
  use_treesitter = true,
  show_current_context = true,
  show_current_context_start = true,
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^do",
    "^switch",
    "^while",
    "jsx_element",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  buftype_exclude = { "terminal", "nofile" },
  filetype_exclude = {
    "alpha",
    "log",
    "gitcommit",
    "dapui_scopes",
    "dapui_stacks",
    "dapui_watches",
    "dapui_breakpoints",
    "dapui_hover",
    "LuaTree",
    "dbui",
    "UltestSummary",
    "UltestOutput",
    "vimwiki",
    "markdown",
    "json",
    "txt",
    "vista",
    "NvimTree",
    "git",
    "TelescopePrompt",
    "undotree",
    "flutterToolsOutline",
    "org",
    "orgagenda",
    "help",
    "startify",
    "dashboard",
    "packer",
    "neogitstatus",
    "Outline",
    "Trouble",
    "lspinfo",
    "", -- for all buffers without a file type
  },
  colorcolumn = "99999",
}
